---
# tasks file for kubeadm_join_worker

- name: Copy kubeadm join configuration
  ansible.builtin.template:
    src: kubeadm_join.yaml.j2
    dest: ~/kubeadm_join.yaml
    mode: "644"
  register: kubeadm_join_config

- name: Join Kubernetes cluster as a worker node
  become: true
  ansible.builtin.command: kubeadm join --config={{ kubeadm_join_config.dest }}
  changed_when: true
  tags:
    - kubeadm_join
