---
# tasks file for k8s_download

- name: Download runc executable
  ansible.builtin.get_url:
    url: "{{ k8s_download_runc_url }}"
    timeout: 90
    dest: "{{ k8s_download_dir }}/runc"
    mode: "755"
  async: 90
  poll: 0
  register: runc_download

- name: Download containerd binary archive
  ansible.builtin.get_url:
    url: "{{ k8s_download_containerd_url }}"
    timeout: 90
    dest: "{{ k8s_download_dir }}/{{ k8s_download_containerd_archive }}"
    mode: "755"
  async: 90
  poll: 0
  register: containerd_download

- name: Download containerd service file
  ansible.builtin.get_url:
    url: "{{ k8s_download_containerd_service_url }}"
    timeout: 90
    dest: "{{ k8s_download_dir }}/containerd.service"
    mode: "644"
  async: 90
  poll: 0
  register: containerd_service_download

- name: Download CNI plugins archive
  ansible.builtin.get_url:
    url: "{{ k8s_download_cni_plugins_url }}"
    timeout: 90
    dest: "{{ k8s_download_dir }}/{{ k8s_download_cni_plugins_archive }}"
    mode: "755"
  async: 90
  poll: 0
  register: cni_plugins_download

- name: Download crictl binary archive
  ansible.builtin.get_url:
    url: "{{ k8s_download_crictl_url }}"
    timeout: 90
    dest: "{{ k8s_download_dir }}/{{ k8s_download_crictl_archive }}"
    mode: "755"
  async: 90
  poll: 0
  register: crictl_download

- name: Wait for downloads to finish
  ansible.builtin.include_tasks: wait.yml
  vars:
    jid: "{{ item }}"
  loop:
    - "{{ runc_download.ansible_job_id }}"
    - "{{ containerd_download.ansible_job_id }}"
    - "{{ containerd_service_download.ansible_job_id }}"
    - "{{ cni_plugins_download.ansible_job_id }}"
    - "{{ crictl_download.ansible_job_id }}"
  tags:
    - wait_download
