---
- name: Obtain installed Flux CLI version
  ansible.builtin.command: flux --version
  register: flux_version_output
  changed_when: false
  ignore_errors: true

- name: Install Flux CLI
  when: not ansible_check_mode and flux_version_output.rc != 0
  become: true
  block:
    - name: Create temporary download directory
      ansible.builtin.tempfile:
        state: directory
      register: download

    - name: Download Flux CLI install script
      ansible.builtin.get_url:
        url: https://fluxcd.io/install.sh
        timeout: 30
        dest: "{{ download.path }}/flux-cli-install.sh"
        mode: "755"

    - name: Run Flux CLI install script
      ansible.builtin.command:
        cmd: "{{ download.path }}/flux-cli-install.sh"
      changed_when: true

- name: Create a flux symlink for root access
  become: true
  ansible.builtin.file:
    src: /usr/local/bin/flux
    dest: /usr/bin/flux
    state: link
    mode: "755"
