---
# tasks file for gitlab_runner

- name: Install Docker
  become: true
  ansible.builtin.import_tasks: docker.yml

- name: Install & configure GitLab Runner
  become: true
  ansible.builtin.import_tasks: gitlab_runner.yml
