---
- name: Create cloud-init snippets directory
  ansible.builtin.file:
    path: /var/lib/vz/snippets
    state: directory
    mode: "755"

- name: Create cloud-init snippets
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /var/lib/vz/snippets/{{ item | regex_replace('[.]j2$', '') }}
    mode: "644"
  loop:
    - dnf_template.yaml.j2
