---
- name: Disable swap for the current session
  become: true
  ansible.builtin.command: swapoff -a
  changed_when: true

- name: Persist disabled swap
  become: true
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: "^(\\s*)([^#\\n]+\\s+)(\\w+\\s+)swap(\\s+.*)$"
    replace: "#\\1\\2\\3swap\\4"
    backup: true
