---
# tasks file for nvidia

- name: Fail if not RedHat family
  ansible.builtin.import_role:
    name: gillwong.homelab.os
  vars:
    os_distro: RedHat

- name: Install NVIDIA GPU driver
  when: ansible_facts['os_family'] == 'RedHat'
  ansible.builtin.import_tasks: rhel.yml

- name: Reboot
  become: true
  ansible.builtin.reboot:
  tags:
    - reboot
