---
# tasks file for base

- name: Fail if not RedHat family
  ansible.builtin.import_role:
    name: gillwong.homelab.os
  vars:
    os_distro: RedHat

- name: Install and configure Kubernetes tools
  when: ansible_facts['os_family'] == 'RedHat'
  ansible.builtin.import_tasks: rhel.yml
