---
# tasks file for kubeadm_join_cp

- name: Copy kubeadm join configuration
  ansible.builtin.template:
    src: kubeadm_join.yaml.j2
    dest: ~/kubeadm_join.yaml
    mode: "644"
  register: kubeadm_join_config

- name: Check if Kubernetes cluster initialized
  ansible.builtin.command: kubectl get --raw='/readyz?verbose'
  ignore_errors: true
  register: kubectl_output
  changed_when: false

- name: Join Kubernetes cluster as a control plane node
  when: kubectl_output.rc != 0
  become: true
  ansible.builtin.command: kubeadm join --config={{ kubeadm_join_config.dest }}
  changed_when: true
