---
# tasks file for calico

- name: Install Tigera operator
  ansible.builtin.command:
    argv:
      - kubectl
      - create
      - --filename={{ calico_tigera_operator_url }}/{{ item }}
  changed_when: true
  loop:
    - operator-crds.yaml
    - tigera-operator.yaml

- name: Wait for Tigera operator to finish installation
  ansible.builtin.command:
    argv:
      - kubectl
      - --namespace=tigera-operator
      - rollout
      - status
      - deployment
      - tigera-operator
      - --timeout=120s
  changed_when: false

- name: Wait
  ansible.builtin.wait_for:
    timeout: 15

- name: Copy Calico installation manifest
  ansible.builtin.template:
    src: calico.yaml.j2
    dest: ~/calico.yaml
    mode: "644"
  register: calico_template_output

- name: Install Calico
  ansible.builtin.command:
    argv:
      - kubectl
      - create
      - --filename={{ calico_template_output.dest }}
  changed_when: true

- name: Wait for calico-system namespace to be created
  ansible.builtin.command:
    argv:
      - kubectl
      - wait
      - --for=create
      - namespace/calico-system
      - --timeout=120s
  changed_when: false

- name: Wait
  ansible.builtin.wait_for:
    timeout: 15

- name: Wait for Calico to finish installation
  ansible.builtin.command:
    argv:
      - kubectl
      - --namespace=calico-system
      - wait
      - --for=jsonpath=.status.numberReady=1
      - daemonset.apps/calico-node
      - --timeout=120s
  changed_when: false
