---
# tasks file for nvidia_containerd

- name: Fail if not RedHat family
  when: ansible_facts['os_family'] != 'RedHat'
  ansible.builtin.fail:
    msg: "This role only supports RedHat family hosts."

- name: Install NVIDIA Container Toolkit and configure containerd
  when: ansible_facts['os_family'] == 'RedHat'
  ansible.builtin.import_tasks: rhel.yml
