---
- name: Enable NVIDIA's Container Toolkit RPM repository
  become: true
  ansible.builtin.command:
    argv:
      - dnf
      - config-manager
      - --add-repo
      - https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo
    creates: /etc/yum.repos.d/nvidia-container-toolkit.repo

- name: Enable NVIDIA's experimental packages
  become: true
  ansible.builtin.command:
    argv:
      - dnf
      - config-manager
      - --enable
      - nvidia-container-toolkit-experimental
  changed_when: true

- name: Install NVIDIA Container Toolkit
  become: true
  ansible.builtin.package:
    name: nvidia-container-toolkit
    state: present

- name: Configure containerd
  become: true
  ansible.builtin.command: nvidia-ctk runtime configure --runtime=containerd
  changed_when: true

- name: Restart containerd
  become: true
  ansible.builtin.service:
    name: containerd
    state: restarted
