---
# defaults file for k8s_download

k8s_download_system_arch: amd64

# runc
k8s_download_runc_version: 1.3.0
k8s_download_runc_url: https://github.com/opencontainers/runc/releases/download/v{{ k8s_download_runc_version }}/runc.{{ k8s_download_system_arch }}

# containerd
k8s_download_containerd_version: 2.1.1
k8s_download_containerd_archive: containerd-{{ k8s_download_containerd_version }}-linux-{{ k8s_download_system_arch }}.tar.gz
k8s_download_containerd_url: https://github.com/containerd/containerd/releases/download/v{{ k8s_download_containerd_version }}/{{ k8s_download_containerd_archive
  }}
k8s_download_containerd_service_url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service

# CNI plugins
k8s_download_cni_plugins_version: 1.7.1
k8s_download_cni_plugins_archive: cni-plugins-linux-{{ k8s_download_system_arch }}-v{{ k8s_download_cni_plugins_version }}.tgz
k8s_download_cni_plugins_url: https://github.com/containernetworking/plugins/releases/download/v{{ k8s_download_cni_plugins_version }}/{{ k8s_download_cni_plugins_archive
  }}

# crictl

k8s_download_crictl_version: 1.33.0
k8s_download_crictl_system_arch: amd64
k8s_download_crictl_archive: crictl-v{{ k8s_download_crictl_version }}-linux-{{ k8s_download_system_arch }}.tar.gz
k8s_download_crictl_url: https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ k8s_download_crictl_version }}/{{ k8s_download_crictl_archive }}
