name: Release

on:
  release:
    types:
      - published
    
jobs:
  release:
    uses: ansible/ansible-content-actions/.github/workflows/release_galaxy.yaml@main
    with:
      environment: release
    secrets:
      ansible_galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
  # release:
  #   uses: ansible/ansible-content-actions/.github/workflows/release_galaxy.yaml@main
  #   with:
  #     environment: release
  #   secrets:
  