---
- name: Create configuration directory
  become: true
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: "755"

- name: Create configuration file
  become: true
  ansible.builtin.template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    mode: "644"

- name: Restart containerd
  become: true
  ansible.builtin.service:
    name: containerd
    state: restarted
    enabled: true
