---
- name: Install runc
  become: true
  ansible.builtin.copy:
    src: "{{ containerd_download_dir }}/runc"
    dest: /usr/local/sbin/runc
    mode: "755"

- name: Create a runc symlink for root access
  become: true
  ansible.builtin.file:
    src: /usr/local/sbin/runc
    dest: /usr/bin/runc
    state: link
    mode: "755"

- name: Extract containerd binary archive
  become: true
  ansible.builtin.unarchive:
    src: "{{ containerd_download_dir }}/{{ containerd_archive }}"
    dest: /usr/local/
    mode: "755"

- name: Create symlink to binaries for root access
  become: true
  ansible.builtin.file:
    src: /usr/local/bin/{{ item }}
    dest: /usr/bin/{{ item }}
    state: link
    mode: "755"
  loop:
    - containerd
    - ctr

- name: Install containerd service
  become: true
  ansible.builtin.copy:
    src: "{{ containerd_download_dir }}/containerd.service"
    dest: /usr/lib/systemd/system/containerd.service
    mode: "644"

- name: Load service
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: containerd
    enabled: true
    state: started

- name: Create CNI plugins directory
  become: true
  ansible.builtin.file:
    path: /opt/cni/bin
    state: directory
    mode: "755"

- name: Extract CNI plugins archive
  become: true
  ansible.builtin.unarchive:
    src: "{{ containerd_download_dir }}/{{ containerd_cni_plugins_archive }}"
    dest: /opt/cni/bin/
    mode: "755"
